apiVersion: apps/v1
kind: Deployment
metadata:
  name: automl-app
  labels:
    app: automl-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: automl-app
  template:
    metadata:
      labels:
        app: automl-app
    spec:
      containers:
        - name: automl-container
          image: automlregistry.azurecr.io/automl-app:latest
          ports:
            - containerPort: 8501
          env:
            - name: STREAMLIT_SERVER_PORT
              value: "8501"
            - name: STREAMLIT_SERVER_ADDRESS
              value: "0.0.0.0"
            - name: STREAMLIT_SERVER_HEADLESS
              value: "true"
            - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
              value: "false"
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          livenessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: models-storage
              mountPath: /app/models
            - name: reports-storage
              mountPath: /app/reports
      volumes:
        - name: models-storage
          emptyDir: {}
        - name: reports-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: automl-service
spec:
  selector:
    app: automl-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer
